{{- /* Module main. */}}
{{ include "okdp.vendor.render" (dict "ctx" . "chart" "spark-history-server" "valuesFile" "vendor-values/spark-history-server.yaml" "values" (include "okdp-shs.values.history" . | fromYaml) "upstream" (include "okdp-shs.upstream.history" . | fromYaml)) }}
