{{- /* Module noname. */}}
{{ include "okdp.vendor.render" (dict "ctx" . "chart" "spark-operator" "valuesFile" "vendor-values/spark-operator.yaml" "values" (include "okdp-spark-operator.values" . | fromYaml) "upstream" (include "okdp-spark-operator.upstream" . | fromYaml)) }}
