{{- /* Module main. */}}
{{ include "okdp.vendor.render" (dict "ctx" . "chart" "trino" "values" (include "okdp-trino.values.trino" . | fromYaml) "upstream" (include "okdp-trino.upstream.trino" . | fromYaml)) }}
